### Attempting to run regressions from systematics values extracted geometrically or from Kitanidis et al on galaxy density


In [15]:
import pandas as pd
import numpy as np
import pickle
import healpy as hp

In [16]:
### Setting Healpy Information
NSIDE = 256
NPIX = hp.nside2npix(NSIDE)
print(
    "Approximate resolution at NSIDE {} is {:.2} deg".format(
        NSIDE, hp.nside2resol(NSIDE, arcmin=True) / 60
    )
)

def raDec2thetaPhi(ra, dec):
    return (0.5 * np.pi - np.deg2rad(dec)), (np.deg2rad(ra))


Approximate resolution at NSIDE 256 is 0.23 deg


### Importing Galaxy Density Information

In [29]:
df_objects = pd.read_csv('../bricks_data/galaxy_catalogue_sample.csv')


In [30]:
df_objects.head()

BrickID  ObjectID          RA        DEC  South  Target_type
0   389675        10  133.284363  10.315927   True            3
1   389675        11  133.284832  10.314327   True            2
2   389675        15  133.285109  10.294865   True            3
3   389675        21  133.285731  10.319199   True            3
4   389675        35  133.286350  10.168023   True            2

In [35]:
# LRG

df_LRG = df_objects[df_objects["Target_type"] == 1]
ra_LRG = df_LRG["RA"].to_numpy(copy=True)
dec_LRG = df_LRG["DEC"].to_numpy(copy=True)
theta, phi = raDec2thetaPhi(ra_LRG, dec_LRG)

print("Number of LRGs in Sample:", len(ra_LRG))

LRG_pixel_indices = hp.ang2pix(NSIDE, theta,phi)


# Finding out unique indices and how often they appear --> shows the density of LRGs in this pixel
(unique, counts) = np.unique(LRG_pixel_indices, return_counts=True)

print(unique)

mean_LRG = counts.mean()
print("Mean LRGs per Pixel:", mean_LRG)
# Calculating Densities for every block
density_LRG = (counts / mean_LRG) - 1
id_density = np.stack((unique, density_LRG), axis=1)
print(id_density)
df_lrg = pd.DataFrame(id_density, columns=['pixel_id', 'lrg_density'])
df_lrg.pixel_id = df_lrg.pixel_id.astype(int)
df_lrg.head()

Number of LRGs in Sample: 41904
[166098 167122 167123 ... 756988 756989 757472]
Mean LRGs per Pixel: 9.93692198245198
[[ 1.66098000e+05  3.08252195e-01]
 [ 1.67122000e+05 -8.99365216e-01]
 [ 1.67123000e+05  4.08886980e-01]
 ...
 [ 7.56988000e+05 -8.99365216e-01]
 [ 7.56989000e+05  1.61650439e+00]
 [ 7.57472000e+05 -4.96826079e-01]]


pixel_id  lrg_density
0    166098     0.308252
1    167122    -0.899365
2    167123     0.408887
3    171167    -0.496826
4    172190    -0.496826

In [36]:
# LRG

df_ELG = df_objects[df_objects["Target_type"] == 2]
ra_ELG = df_ELG["RA"].to_numpy(copy=True)
dec_ELG = df_ELG["DEC"].to_numpy(copy=True)
theta, phi = raDec2thetaPhi(ra_ELG, dec_ELG)

print("Number of ELGs in Sample:", len(ra_ELG))

ELG_pixel_indices = hp.ang2pix(NSIDE, theta,phi)


# Finding out unique indices and how often they appear --> shows the density of LRGs in this pixel
(unique, counts) = np.unique(ELG_pixel_indices, return_counts=True)

print(unique)

mean_ELG = counts.mean()
print("Mean ELGs per Pixel:", mean_ELG)
# Calculating Densities for every block
density_ELG = (counts / mean_ELG) - 1
id_density = np.stack((unique, density_ELG), axis=1)
print(id_density)
df_elg = pd.DataFrame(id_density, columns=['pixel_id', 'elg_density'])
df_elg.pixel_id = df_elg.pixel_id.astype(int)

print(df_elg.head())

Number of ELGs in Sample: 157118
[166098 167122 167123 ... 756502 756989 757472]
Mean ELGs per Pixel: 32.556568586821385
[[ 1.66098000e+05  7.50518718e-02]
 [ 1.67122000e+05 -9.07852697e-01]
 [ 1.67123000e+05 -4.16400412e-01]
 ...
 [ 7.56502000e+05 -5.69979251e-01]
 [ 7.56989000e+05  4.34454359e+00]
 [ 7.57472000e+05  1.36203363e-02]]
   pixel_id  elg_density
0    166098     0.075052
1    167122    -0.907853
2    167123    -0.416400
3    171167     0.412925
4    172190    -0.293537


In [46]:
df_QSO = df_objects[df_objects["Target_type"] == 3]
ra_QSO = df_QSO["RA"].to_numpy(copy=True)
dec_QSO = df_QSO["DEC"].to_numpy(copy=True)
theta, phi = raDec2thetaPhi(ra_QSO, dec_QSO)

print("Number of QSOs in Sample:", len(ra_QSO))

QSO_pixel_indices = hp.ang2pix(NSIDE, theta,phi)


# Finding out unique indices and how often they appear --> shows the density of LRGs in this pixel
(unique, counts) = np.unique(QSO_pixel_indices, return_counts=True)

print(unique)

mean_QSO = counts.mean()
print("Mean QSOs per Pixel:", mean_QSO)
# Calculating Densities for every block
density_QSO = (counts / mean_QSO) - 1
id_density = np.stack((unique, density_QSO), axis=1)
print(id_density)
df_qso = pd.DataFrame(id_density, columns=['pixel_id', 'qso_density'])
df_qso.pixel_id = df_qso.pixel_id.astype(int)

print(df_qso.head())

Number of QSOs in Sample: 180394
[166098 167122 167123 ... 756502 756989 757472]
Mean QSOs per Pixel: 36.92058943921408
[[ 1.66098000e+05  5.63211637e-02]
 [ 1.67122000e+05 -8.10403894e-01]
 [ 1.67123000e+05  1.10491480e-01]
 ...
 [ 7.56502000e+05 -8.64574210e-01]
 [ 7.56989000e+05  2.60232602e+00]
 [ 7.57472000e+05 -1.60360101e-01]]
   pixel_id  qso_density
0    166098     0.056321
1    167122    -0.810404
2    167123     0.110491
3    171167    -0.024934
4    172190    -0.133275


In [48]:
df = pd.merge(df_lrg, df_elg, how='outer', on='pixel_id')
df = pd.merge(df, df_qso, how='outer', on='pixel_id')
print(df.isna().sum())
print(df_lrg.shape, df_elg.shape, df_qso.shape, df.shape)

pixel_id         0
lrg_density    860
elg_density    251
qso_density    191
dtype: int64
(4217, 2) (4826, 2) (4886, 2) (5077, 4)


In [49]:
# Dropping all pixels where I do not have densities for all 3 types of galaxies
df.dropna(axis=0, inplace=True)
df.shape

(4096, 4)